services:
  - type: web
    name: pos-happy
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_STATE_TABLE
        value: pos_happy_state
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
